# -*- coding: utf-8 -*-
"""Web_Scraping_Flipkart_com.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ir1NlCKLVxP5cd_YblOY3RKQmmCeUXSO
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import csv

url="https://www.flipkart.com/search?q=laptops&sid=6bo%2Cb5g&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_6_sc_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_6_sc_na_na&as-pos=2&as-type=RECENT&suggestionId=laptops%7CLaptops&requestId=0f60f509-3725-4bad-bb7a-38ce00929d97&as-searchtext=laptops"

req=requests.get(url)

soup= BeautifulSoup(req.content,'html.parser')

data=soup.find_all('div', attrs={'class':'_4rR01T' })

print(data)

products=[]
prices=[]
ratings=[]
data=soup.find_all('div', attrs={'class':'_4rR01T' })
print(data)

for a in soup.find_all('a',href=True,attrs={'class':'_1fQZEK'}):
      name=a.find('div',attrs={'class':'_4rR01T'})
      price=a.find('div',attrs={'class':'_30jeq3 _1_WHN1'})
      rating=a.find('div',attrs={'class':'_3LWZlK'})
      products.append(name.text)
      prices.append(price.text)
      ratings.append(rating.text)

df=pd.DataFrame({"Product Name ":products,'Prices':prices,'ratings':ratings})
df.head(250)

df.to_csv('Products.csv')